version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --worker-class=gthread --workers=3 --threads=3 core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/static
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=secretkey
    depends_on:
      - redis
      - db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - redis
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/static

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
      - db

    celery-beat:
      build: .
      command: celery -A core beat -l info
      volumes:
        - ./core:/app
      depends_on:
        - redis
        - backend
        - db
      environment:
        - DEBUG=0
        - SECRET_KEY=secretkey

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "1433:1433"
    volumes:
      - ./core:/app/var/lib/mysql

volumes:
  static_volume:
  media_volume: